# Generated by Django 2.1.4 on 2018-12-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_section', models.CharField(max_length=50)),
                ('item_country', models.CharField(max_length=30)),
                ('item_barcode', models.CharField(max_length=12)),
                ('item_cost', models.IntegerField()),
                ('item_number', models.IntegerField()),
                ('vision', models.BooleanField(default=False)),
            ],
        ),
    ]
