# Generated by Django 2.1.4 on 2018-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_card',
            name='item_photo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
