# Generated by Django 2.1.4 on 2018-12-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_product_card_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_card',
            name='item_photo',
        ),
    ]
