# Generated by Django 2.1.4 on 2018-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_remove_product_card_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_card',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
