# Generated by Django 2.1.4 on 2018-12-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_product_card_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
