# Generated by Django 2.1.4 on 2018-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20181220_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
