# Generated by Django 2.1.4 on 2018-12-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_bin_user_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_bin',
            name='id_bin',
        ),
        migrations.RemoveField(
            model_name='user_bin',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_bin',
        ),
    ]
