# Generated by Django 2.1.4 on 2018-12-21 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0010_auto_20181221_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.bin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
