# Generated by Django 2.1.4 on 2018-12-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_auto_20181222_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='req_bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.bin')),
                ('id_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.journal_request')),
            ],
        ),
    ]
