# Generated by Django 2.1.4 on 2018-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_req_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
