# Generated by Django 2.1.4 on 2018-12-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_journal_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
