# Generated by Django 2.1.4 on 2018-12-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='data',
            new_name='date',
        ),
    ]
